import { prisma } from '@buildora/database';
import { ensureCommerceSchema, type CommerceProductRow } from '../../../../../../server/commerce';
import { ensureHackathonSchema, jsonError } from '../../../../../../server/hackathon';

type TiptapNode = { type?: string; attrs?: { level?: number }; text?: string; content?: TiptapNode[] };

function textOf(node?: TiptapNode) {
  if (!node) return '';
  if (node.type === 'text') return node.text || '';
  return (node.content || []).map(textOf).join('').trim();
}

function slugify(value: string) {
  return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 70);
}

async function ensureStarterProducts(siteId: string) {
  const rows = await prisma.$queryRawUnsafe<Array<{ count: number }>>(
    "SELECT COUNT(*) as count FROM commerce_products WHERE siteId = ? AND status = 'PUBLISHED'",
    siteId,
  );
  if (Number(rows[0]?.count || 0) > 0) return;

  const page = await prisma.page.findFirst({ where: { siteId, slug: 'products', status: 'PUBLISHED' } });
  if (!page?.contentJson || typeof page.contentJson !== 'object') return;
  const doc = page.contentJson as unknown as TiptapNode;
  const nodes = Array.isArray(doc.content) ? doc.content : [];
  const items: Array<{ name: string; description: string }> = [];
  for (let index = 0; index < nodes.length; index += 1) {
    const node = nodes[index];
    if (node.type === 'heading' && node.attrs?.level === 2) {
      const name = textOf(node);
      const description = nodes[index + 1]?.type === 'paragraph' ? textOf(nodes[index + 1]) : '';
      if (name) items.push({ name, description });
    }
  }

  const starterPrices = [850000, 1250000, 1800000, 950000, 1500000, 2200000];
  for (const [index, item] of items.slice(0, 6).entries()) {
    await prisma.$executeRawUnsafe(
      'INSERT OR IGNORE INTO commerce_products (id, siteId, name, slug, description, price, currency, imageUrl, stockQuantity, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
      crypto.randomUUID(),
      siteId,
      item.name.slice(0, 120),
      slugify(item.name) || `product-${index + 1}`,
      (item.description || 'A starter product generated by Buildora AI.').slice(0, 3000),
      starterPrices[index] ?? 1000000,
      'NGN',
      null,
      12,
      'PUBLISHED',
    );
  }
}

export async function GET(_: Request, { params }: { params: { slug: string } }) {
  try {
    await ensureHackathonSchema();
    await ensureCommerceSchema();
    const site = await prisma.site.findUnique({ where: { slug: params.slug }, select: { id: true, name: true, slug: true, themeConfig: true } });
    if (!site) return jsonError('Site not found', 404);
    await ensureStarterProducts(site.id);
    const products = await prisma.$queryRawUnsafe<CommerceProductRow[]>(
      "SELECT * FROM commerce_products WHERE siteId = ? AND status = 'PUBLISHED' ORDER BY createdAt DESC",
      site.id,
    );
    return Response.json({ site, products });
  } catch {
    return jsonError('Unable to load storefront', 500);
  }
}
